name: pinch_to_zoom_scrollable_example
description: An example for pinch_to_zoom_scrollable

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pinch_to_zoom_scrollable:
    path: ../
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/